stages:
  get_data:
    cmd: python src/stage_01_get_data.py --config=configs/config.yaml
    deps:
    - src/stage_01_get_data.py
    - configs/config.yaml
    outs:
    - data/X_train_full.npy
    - data/X_test.npy
    - data/y_train_full.npy
    - data/y_test.npy

  prepare_base_model:
    cmd: python src/stage_02_prepare_base_model.py --config=configs/config.yaml --params=params.yaml
    deps:
    - src/stage_02_prepare_base_model.py
    - src/utils/common.py
    - src/utils/model.py
    - configs/config.yaml
    params:
    - LEARNING_RATE
    outs:
    - artifacts/model/model.h5

  prepare_callback:
    cmd: python src/stage_03_prepare_callback.py --config=configs/config.yaml
    deps:
    - src/stage_03_prepare_callback.py
    - src/utils/common.py
    - src/utils/callbacks.py
    - configs/config.yaml
    - params.yaml
    outs:
    - artifacts/callbacks/checkpoint_cb.cb
    - artifacts/callbacks/tensorboard_cb.cb

  train:
    cmd: python src/stage_04_train.py --config=configs/config.yaml --params=params.yaml
    deps:
    - src/stage_04_train.py
    - src/utils/common.py
    - src/utils/model.py
    - src/utils/callbacks.py
    - src/utils/data_management.py
    - configs/config.yaml
    - artifacts/callbacks/checkpoint_cb.cb
    - artifacts/callbacks/tensorboard_cb.cb
    - artifacts/model/model.h5
    - data/X_train_full.npy
    - data/y_train_full.npy
    params:
    - BATCH_SIZE
    - EPOCHS
    outs:
    - artifacts/trained_model
    - artifacts/tensorboard_log_dir
    - artifacts/checkpoints

  evaluate:
    cmd: python src/stage_05_evaluate.py --config=configs/config.yaml
    deps:
    - src/stage_05_evaluate.py
    - src/utils/common.py
    - configs/config.yaml
    - artifacts/trained_model/trained_model.h5
    - data/X_test.npy
    - data/y_test.npy
    metrics:
    - scores.json:
        cache: false
    plots:
    - prc.json:
        cache: false
        x: recall
        y: precision
    - roc.json:
        cache: false
        x: fpr
        y: tpr
