artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: trained_model
  MODEL_DIR: model
  MODEL_NAME: model.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: model_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks
  DATA_DIR: data


local_data_dirs:
  - data

plots:
  PRC: prc.json
  ROC: roc.json

metrics:
  SCORES: scores.json